## See https://dev.azure.com/cdcbigdatademo/DEMO_SHARED/_git/azure_devops_resources
resources:
  repositories:
    - repository: tox
      type: github
      endpoint: github
      name: tox-dev/azure-pipelines-template
      ref: refs/tags/0.1

trigger:
  batch: true

stages:
  - stage: test
    displayName: Test issue
    jobs:
      - job: test_job
        displayName: Run simple steps
        pool:
          vmImage: ubuntu-latest
        steps:

          - task: Bash@3
            displayName: 'This is a simple test task'
            inputs:
              targetType: 'inline'
              script: |
                echo "Hello world !"
          # Maven v3
          # Build, test, and deploy with Apache Maven.
          - task: Maven@3
            displayName: This is simple maven task to illustrate the version update
            inputs:
              mavenPOMFile: 'pom.xml' # string. Required. Maven POM file. Default: pom.xml.
              goals: "help:evaluate -Dexpression='project.description' --no-transfer-progress" # string. Goal(s). Default: package.
              # JUnit Test Results
              publishJUnitResults: false # boolean. Publish to Azure Pipelines. Default: true.
